FROM node:alpine as build
WORKDIR /app
# package.json을 복사해서 디펜던시를 재설정 및 설치하는 레이어를 분리하여 최적화
COPY package.json . 
# npm 업그레이드를 수행하라고 도커가 시켜서...ㅠ
RUN npm install -g npm@8.19.0
# 버전 오류 해결을 위해 옵션
RUN npm install --save --legacy-peer-deps 
# 전체 파일 복사
COPY . .
#ARG REACT_APP_NAME
#ENV REACT_APP_NAME=$REACT_APP_NAME
RUN npm run build

FROM nginx as produce
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html